# Configuration du plugin de RandomTP par Enzoooo_

# Réglages de la portée du randomTP depuis le spawn du monde
distance-max: 2500
distance-min: 300

# Réglages du temps du cooldown
cooldown: 30
