name: RandomTP
author: Enzoooo_
version: 1.2
api-version: 1.16
main: fr.enzoooo.randomtp.Main

commands:
  rtp:
    aliases: randomtp
    description: Vous téléporte aléatoirement sur la map
    permission: randomtp.use
  rconfig:
    description: Permet de reload la configuration du plugin
    permission: randomtp.reload